[package]
name = "cli"
version = "0.1.6"
edition = "2024"

[dependencies]

indexer = { path = "../indexer" }
query = { path = "../query" }
storage = { path = "../storage" }
parser = { path= "../parser" }
clap = { version = "4.5", features = ["derive"] }
semantic = { path = "../semantic" }
analytics = { path = "../analytics" }

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = {version = "1.52.3", features = ["full"]}
rusqlite = "0.40.1"
regex = "1.12.4"
graph = { version = "0.1.0", path = "../graph" }
graph_diagnostics = { path = "../graph_diagnostics" }
rayon = "1.10"
indicatif = "0.17"
self_update = { version = "0.44.0", features = ["archive-tar", "archive-zip", "compression-flate2", "compression-zip-deflate"] }
reqwest = { version = "0.13.4", features = ["blocking"] }
tempfile = "3.27.0"
self-replace = "1.5.0"

[[bin]]
name = "codebroker"
path = "src/main.rs"
